name: llmrl
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - expat=2.7.1
  - faiss=1.8.0
  - faiss-cpu=1.8.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=19.1.7
  - libexpat=2.7.1
  - libfaiss=1.8.0
  - libffi=3.4.6
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libopenblas=0.3.30
  - libsqlite=3.50.4
  - libzlib=1.3.1
  - llvm-openmp=19.1.7
  - ncurses=6.5
  - openssl=3.5.2
  - packaging=25.0
  - pip=25.1
  - python=3.11.13
  - python_abi=3.11
  - readline=8.3
  - setuptools=78.1.1
  - tk=8.6.13
  - wheel=0.45.1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.10.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.2.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - fastapi==0.116.1
      - filelock==3.19.1
      - fonttools==4.59.1
      - fsspec==2025.7.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.24.6
      - idna==3.10
      - isodate==0.6.1
      - jinja2==3.1.6
      - joblib==1.5.1
      - kiwisolver==1.4.9
      - markupsafe==3.0.2
      - matplotlib==3.10.5
      - mpmath==1.3.0
      - networkx==3.5
      - nltk==3.9.1
      - numpy==2.0.2
      - owlrl==6.0.2
      - pandas==2.3.2
      - pillow==11.3.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydantic-settings==2.10.1
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - rdflib==6.3.2
      - regex==2025.7.34
      - requests==2.31.0
      - safetensors==0.6.2
      - scikit-learn==1.7.1
      - scipy==1.14.1
      - sentence-transformers==2.2.2
      - sentencepiece==0.2.1
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.47.2
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tokenizers==0.19.1
      - torch==2.8.0
      - torchvision==0.23.0
      - tqdm==4.67.1
      - transformers==4.41.1
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==1.26.19
      - uvicorn==0.35.0
variables:
  KMP_DUPLICATE_LIB_OK: 'TRUE'
  OMP_NUM_THREADS: '1'
prefix: /Users/turzo/anaconda3/envs/llmrl
